### ISSUE TITLE
"use strict" angularjs

### ISSUE THREAD

**Issue by JohannesHoffmann** [salbahra/cordova-plugin-networkinterface#11]
I tried to use this plugin to get the local ip address.
inside a angular2 (maybe also angular1) application the console shows a lot of errors.
i figured out that "use strict" will be added by transpiler typescript or other javascript compilers.
Is it possible to fix the plugin to work with "use strict"?
Does someone has the same issue?

**Comment by salbahra** [comment]
Which errors are you referring to? The JS portion of the plugin is only 8 lines of code, hard to imagine a lot of errors being generated due to that. If you could share I can take a look.

**Comment by khakserahul** [comment]
networkinterface.getIPAddress(function (ip) { alert(ip); });
Error
ReferenceError: networkinterface is not defined

**Comment by dhavalshah007** [comment]
any update on this ??

**Comment by salbahra** [comment]
Please add the following line to your TypeScript before referencing the plugin:

`declare var networkinterface: any;`

**Comment by dhavalshah007** [comment]
i have used this line. But still not working.

**Comment by salbahra** [comment]
Please share a code snippet that does not work. Something I can run and reproduce the issue your seeing.

**Comment by dhavalshah007** [comment]
```
declare var networkinterface:any;	
@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  public rootPage:any = HomePage;

platform.ready().then(() => {
    networkinterface.getWiFiIPAddress(function(ip){
	console.log(ip);
	this.toast.show(ip, '2000', 'bottom').subscribe(
	    toast => {
	    	    console.log(toast);
	    });
    });
}
```

Error :
`ReferenceError: networkinterface is not defined.`

In Mobile, Toast Notification is not coming , and in browser I am getting above error.

**Comment by JFernandoGomez** [comment]
same as @dhavalshah007
