### ISSUE TITLE
Feature Request: Netmask

### ISSUE THREAD

**Issue by JohannesHoffmann** [salbahra/cordova-plugin-networkinterface#12]
Would it be possible to add a function to also get the netmask of the network?
I use this plugin to get the ip address to scan a network for a server. To get the whole range of the network i use this plugin: [IPSubnetCalculator](https://github.com/franksrevenge/IPSubnetCalculator)
To geht the range i need the netmask. 
Would be nice to get this feature in here ;)

**Comment by schulti** [comment]
Hi! I agree it would be great to have the netmask available through this plugin.

**Comment by salbahra** [comment]
I think to avoid a soup of callbacks we can probably return the netmask in the IP request as a seperate argument in the callback.

**Comment by wangshug** [comment]
I had the similar case, I need a netmask to calculate broadcast address

**Comment by dharders** [comment]
Just added PR #24 that adds the requested netmask/subnet support.
For now, only iOS and Android have been added.

Please test it out on your devices (by following the PR instructions) and let me know if you find an issue. Hopefully this PR is approved and merged soon. Enjoy!
