### ISSUE TITLE
Doesn't work on cell network / ios

### ISSUE THREAD

**Issue by siddiq** [salbahra/cordova-plugin-networkinterface#14]
For the cell/3g network I get the onError callback with null.
But on WiFi I am successfully able to get the IP in the onSuccess callback.

Platform: iOS 9.x

**Comment by JohannesHoffmann** [comment]
this plugin is only for wifi network connection. For cellular you need a Server Request (with php) wich sends you yor current ip address back to the phone.

**Comment by siddiq** [comment]
Thanks
