### ISSUE TITLE
add support Windows 10 Universal Platform?

### ISSUE THREAD

**Issue by Zorgatone** [salbahra/cordova-plugin-networkinterface#15]
On Windows 10 I get the error `Missing Command Error` when calling getIPAddress. I guess you support only WP8 right?

Could you add the same functionality for Windows 10 please?

**Comment by salbahra** [comment]
This should be possible using this method: https://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.connectivity.networkinformation.gethostnames

**Comment by airimiea** [comment]
Any plans for supporting Windows 10 Universal Platform?

**Comment by salbahra** [comment]
Yes, I will try and look into this soon and update as soon as possible. Thank you for the interest!

**Comment by phoyer** [comment]
This will work for UWP:

`Windows.Networking.Connectivity.NetworkInformation.getHostNames().forEach(host);

function host(element, index, array)
{
    if (element.ipInformation != null)
    {
        if (element.type == 1)
        {
            navigator.notification.alert(element.toString());
        }
}`

On mobile devices it will return several 169. addresses in addition to the correct one. You may want to filter this. In my app I am using your plugin for iOS/Android and then this code inline "if Windows" as I had not time to include it in the plugin. If you or someone else wants to do that, this would be great of course.

**Comment by lordjabez** [comment]
I added Windows 10 support in this pull request: https://github.com/salbahra/cordova-plugin-networkinterface/pull/21

**Comment by salbahra** [comment]
Thank you @lordjabez for PR #21. It has been merged in now.

**Comment by lordjabez** [comment]
@salbahra I just realized you may want to edit the readme to mention Windows 10 support.
