### ISSUE TITLE
First IP is not always the most relevant one

### ISSUE THREAD

**Issue by jeffaries** [salbahra/cordova-plugin-networkinterface#2]
Hi,

When I use your plugin, I get an IP address that is not the actual one. I get a 10.0.x.x IP while my device info shows an 192.168.x.x (my dhcp configuration)

When I read your code, I see that you return the first address found.... could you return every addresses in getIPAddresses?

Thx and good job!!!

**Comment by artuska** [comment]
Well, it is 2019 now and still i get private network IP address like `10.x.x.x`.
