### ISSUE TITLE
Publish v1.1.0 to npm (currently only 1.0.8 published)

### ISSUE THREAD

**Issue by dharders** [salbahra/cordova-plugin-networkinterface#23]
Hey great plugin!

I followed your README instructions to use the new `getWiFiIPAddress()` and `getCarrierIPAddress()` instead of the old deprecated `getIPAddress()` but it didn't work as I used `cordova plugin add cordova-plugin-networkinterface`, which according to npm is only at version 1.0.8. Apparently the newer functions aren't defined in that version.

I guess the solution is to publish the latest version to npm or update your README to add from git master so your users aren't left confused.

Thanks again for the great plugin!

**Comment by salbahra** [comment]
Thank you for noticing this! I am going to update the plugin after I merge in your PR. Thank you for your contributions!!

**Comment by salbahra** [comment]
Okay version 1.2.0 should now be published to NPM fixing the above issue and also adding the new PR changes for subnet into the plugin.

Thanks again!

**Comment by dharders** [comment]
Great! Thanks!
