### ISSUE TITLE
How to use in Ionic?

### ISSUE THREAD

**Issue by nicothed** [salbahra/cordova-plugin-networkinterface#28]
Hi, this plugin looks exactly like what I need, but I'm not fully sure how to use it in Ionic... any idea? How can I access this object?

**Comment by salbahra** [comment]
I have added support to `@ionic-native/network-interface` via this PR https://github.com/ionic-team/ionic-native/pull/2063. In the meantime you can declare the window reference as any in TypeScript to allow use as shown in this issue: https://github.com/salbahra/cordova-plugin-networkinterface/issues/19

**Comment by salbahra** [comment]
You can now reference this plugin using `@ionic-native/network-interface`:

```ts
import { NetworkInterface } from '@ionic-native/network-interface';
 constructor(private networkInterface: NetworkInterface) { }
 ...
this.networkInterface.getWiFiIPAddress(function (ip) { alert(ip); });
this.networkInterface.getCarrierIPAddress(function (ip) { alert(ip); });```
