### ISSUE TITLE
Unable to fetch the CarrierIPAddress

### ISSUE THREAD

**Issue by venuchiluveru** [salbahra/cordova-plugin-networkinterface#31]
Hi,
I'm unable to fetch the CarrierIPAddress

Getting error response as : **No valid IP address identified**

**Comment by salbahra** [comment]
Just did a huge update based on another developers work. Please try again and if the issue persists please re-open. Thanks!

**Comment by lpsBetty** [comment]
@salbahra I just installed the plugin and got the same problem on Android
