### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by Story5** [salbahra/cordova-plugin-networkinterface#34]
In my code, I put the `getIPAddress` function in platform.ready()
```
constructor(
    public platform: Platform,
    public networkInterface:NetworkInterface
) {
   this.platform.ready().then(() => {
      this.networkInterface.getIPAddress().then(ipAddress => {
        console.log("ip-success:", ipAddress);
      }).catch(error => {
        console.error("ip-error:",error);
      });
    });
}
```
When I run these code on ios device, I get these console.warn 
> console.warn: "Native: tried calling NetworkInterface.getIPAddress, but the NetworkInterface plugin is not installed. "
console.warn: Install the NetworkInterface plugin: 'ionic cordova plugin add cordova-plugin-networkinterface'

and my error print
> console.error: ip-error:plugin_not_installed 

It says the plugin is not installed, however, I have added the plugin before and these is related plugin configuration in config.xml file.

**Comment by AishApp** [comment]
I am facing the similar issue with the plugin. kindly help

**Comment by ryaa** [comment]
The error plugin_not_installed seems to happen because there is no getIPAddress method in the plugin. There is type definition in index.d.ts which describes this method however if you look at the plugin networkinterface.js there is no such method. It only has getWiFiIPAddress, getCarrierIPAddress and getHttpProxyInformation method with success/fail callbacks. You may use them as below
```
    public getIPAddrress(): Promise<string> {

        return new Promise((resolve: Function, reject: Function) => {
            (<any>this.networkInterface).getCarrierIPAddress((ipAddress: string) => {
                resolve(ipAddress);
            }, (error) => {
                (<any>this.networkInterface).getWiFiIPAddress((ipAddress: string) => {
                    resolve(ipAddress);
                }, (error) => {
                    reject(error);
                });
            });
        });
});
```

**Comment by salbahra** [comment]
This method has been added back. The methods got split due to changes in the past but a helper method to call the other two methods has now been added.

Thank you for your reports and patience. An update to the npm package will be out shortly.
