### ISSUE TITLE
How to process IP address returned by getWiFiIPAddress()?

### ISSUE THREAD

**Issue by prachi231119** [salbahra/cordova-plugin-networkinterface#35]
If I run` getWiFiIPAddress()` in the browser by running `ionic cordova run browser`, then alert shows IP address but if I run the same App is built for Android platform by `ionic cordova run android` and check DevTools in chrome for logs, an object is displayed.
If I try to access `.ip` and `.subnet`, it says that the properties do no exist.
Please help!

**Comment by lordjabez** [comment]
I've seen similar behavior. The general issue seems to be that the various platform-specific implementations are out of sync with each other, and also out of sync with the Ionic native plugin implementation here: https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/network-interface/index.ts

Note in the above link the type declared for the functions' returned Promise is `string`. That means the plugin fails to pass the Typescript compiler. My recommendation is to change them to `any` (which makes them more flexible).

The documentation is also rather out-of-date, in particular the instructions for the Ionic native plugin are wrong. The functions return promises, they do not accept callbacks.

**Comment by lordjabez** [comment]
FYI, I have the above changes mostly made, I'll make pull requests here shortly.

**Comment by salbahra** [comment]
#36 has been merged in to address this
