### ISSUE TITLE
networkinterface is undefined

### ISSUE THREAD

**Issue by wwwizzarrdry** [salbahra/cordova-plugin-networkinterface#41]
Using the Quasar framework and wanted to easily grab the devices IP.

In the `src-cordova` folder I ran:
`cordova plugin add cordova-plugin-networkinterface`

Added `<plugin name="cordova-plugin-networkinterface" source="npm" />` to the config.xml

Then, once the Vue component is mounted, I run: 
`networkinterface.getWiFiIPAddress( onSuccess, onError );`

But **networkinterface** is always undefined. I thought this plugin added a global reference to networkinterface?

**Comment by Mimateam** [comment]
Try using it as `window.networkinterface`.

**Comment by wwwizzarrdry** [comment]
> Try using it as `window.networkinterface`.
Pretty sure I tried that as well before posting, but it has been a while since I visited that project. I'll check the code and try again. Thanks for the tip.
