### ISSUE TITLE
getWiFiIPAddress sometimes returns 0.0.0.0 on iOS (solution included)

### ISSUE THREAD

**Issue by qpwr** [salbahra/cordova-plugin-networkinterface#46]
This plugin doesn't seem to be maintained anymore, but in case anyone is using it and experiencing the issue mentioned in the title: This is because the plugin just goes through all en0 interfaces (which is wifi) and uses always the last one. It seems that there is sometimes more than one en0, but some of them with IP 0.0.0.0 (probably non-active ones). If one of the 0.0.0.0 happen to be looped through **after** the actual active en0 interface, the returned IP will be 0.0.0.0.

To patch this, you have to make some changes to ```CDVNetworkInterface.m```, line 22 (within the ```getInterfaceiIP``` function):

Search for 

```if([name isEqualToString:interfaceName]```

and change it to 

```if([name isEqualToString:interfaceName] && ![addr isEqualToString:@"0.0.0.0"])```

Hope someone finds this helpful.

**Comment by salbahra** [comment]
Just added this change, thank you for this issue and solution!

**Comment by Bastien3093** [comment]
Hello ! Your latest version generates build errors on iOS

_cordova-plugin-networkinterface/CDVNetworkInterface.m **expected identifier or '('**_
and
_cordova-plugin-networkinterface/CDVNetworkInterface.m **extraneous closing brace ('}')**_

**Comment by salbahra** [comment]
Ah darn must have been a bad merge, let me take a look at this today.

Thank you for the heads up!
Samer

**Comment by salbahra** [comment]
Should be fixed in 2.2.0! Thank you very much!

**Comment by Bastien3093** [comment]
Amazing ! Thanks to you :)
