### ISSUE TITLE
Cannot install cordova plugin on with never cordova-android versions

### ISSUE THREAD

**Issue by DaedalusAB** [salbahra/cordova-plugin-networkinterface#47]
Hi, 

When I try to do cordova plugin add, I get this error:

` ENOENT: no such file or directory, open '/Users/abu/Desktop/Solutions/neonbanking-frontend/node_modules/cordova-android/bin/templates/app/src/main/AndroidManifest.xml'`

The same error appears on cordova-android 9.0.0 and 10.1.1

When I open the directory of cordova-android in node_modules, the manifest is there, but at a slightly different path. 

Could it be that this plugin doesn't work on certian cordova-android versions?

**Comment by salbahra** [comment]
Try deleting the entire `platforms` directory then again trying `cordova platform add android`.

Otherwise, follow up with Cordova team seems to be an issue on that side.
