### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [salbahra/cordova-plugin-networkinterface#7]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...your plugin should be move to npm in the future...

**Comment by salbahra** [comment]
I was never using plugins.corodva.io however I did go ahead and post the project on NPM.

Link: https://www.npmjs.com/package/cordova-plugin-networkinterface

Thanks.

**Comment by bau720123** [comment]
hi @salbahra 
really thanks your reply
thanks again~
