### ISSUE TITLE
Any usable example I can use like reference

### ISSUE THREAD

**Issue by eeijcea** [salbahra/cordova-plugin-networkinterface#8]
Hi Samer,

I trying to use your plugin... I can see alert in sample function you provide comes with information but I am unable to modify it at all.  The simple change of assigning ip to a different variable does not work ...alert in the code below comes always with info ... but variable afterwards remains undefined. Any guidelines where to look for will be greatly appreciated.

var ownIP;
function setOwnIP(){
	networkinterface.getIPAddress(function (ip) { alert(ip); ownIP = ip; });
}

rgds
Juan Antonio

**Comment by jrtaylor-com** [comment]
The issue you are experiencing is because the method is asynchronous and hasn't resolved yet when you are reading the ownIP variable. A good reference for getting around this can be found here: http://stackoverflow.com/questions/14220321/how-do-i-return-the-response-from-an-asynchronous-call

**Comment by eeijcea** [comment]
Hi James,

Thanks for the advise, I followed different approach already .. I created a recurrent timer of a few milliseconds to validate when variable was defined and regular event trigger to signal after success. it is working OK now.

Rgds,
Juan Antonio
